Repository naimulcsx/progHours, pull requests merged in 2022-04, with the labels that each got.

#134 Add Online Judge Handle on Settings
  client/src/api/handle.ts
  client/src/components/Form.tsx
  client/src/components/submissions/Table.tsx
  client/src/pages/settings/AccountSettings.tsx
  client/src/pages/settings/HandleSettings.tsx
  server/src/modules/handles/handles.controller.ts
  server/src/modules/handles/handles.entity.ts
  server/src/modules/handles/handles.module.ts
  server/src/modules/handles/handles.service.ts
  server/src/modules/online-judges/online-judges.module.ts
  server/src/modules/users/users.service.ts
  server/src/validators/create-handle-dto.ts
  server/test/fake-db-seed.ts
Labels: frontend, backend

#139 Fix TypeScript errors in client
  client/src/GlobalStateProvider.tsx
  client/src/components/AuthContainer.tsx
  client/src/components/DropdownMenu.tsx
  client/src/components/Logo.tsx
  client/src/components/NavLink.tsx
  client/src/components/Navbar.tsx
  client/src/components/SettingsLayout.tsx
  client/src/components/dashboard/Sidebar.tsx
  client/src/components/leaderboard/Table.tsx
  client/src/components/submissions/Table.tsx
  client/src/components/submissions/columns/Actions.tsx
  client/src/components/submissions/columns/DatePicker.tsx
  client/src/components/submissions/columns/ProblemName.tsx
  client/src/components/submissions/columns/SolveTime.tsx
  client/src/components/submissions/columns/Tags.tsx
  client/src/components/submissions/columns/Verdict.tsx
  client/src/favicon.svg
  client/src/hooks/useSubmissions.ts
  client/src/hooks/useUser.ts
  client/src/pages/dashboard/Home.tsx
  client/src/pages/leaderboard/index.tsx
  client/src/types/Practice.ts
  client/src/types/Problem.ts
  client/src/types/RanklistItem.ts
  client/src/types/Submission.ts
  client/src/types/Tag.ts
  client/src/types/UserProblemTag.ts
  client/src/types/react-table-config.d.ts
  client/tsconfig.json
  server/src/modules/auth/auth.controller.ts
Labels: frontend

#144 Update parsers
  client/src/components/Icons.tsx
  client/src/components/submissions/columns/ProblemName.tsx
  server/src/modules/parsers/parsers.service.ts
  server/src/modules/submissions/submissions.service.ts
Labels: backend

#147 Refactor backend
  client/package.json
  client/src/App.tsx
  client/src/api/dashboard.ts
  client/src/api/leaderboard.ts
  client/src/api/submissions.ts
  client/src/api/user.ts
  client/src/components/Navbar.tsx
  client/src/components/ProgressBox.tsx
  client/src/components/Spinner.tsx
  client/src/components/dashboard/Layout.tsx
  client/src/components/dashboard/stats/VerdictChart.tsx
  client/src/components/leaderboard/Table.tsx
  client/src/components/profile/Table.tsx
  client/src/components/submissions/Table.tsx
  client/src/components/submissions/columns/Tags.tsx
  client/src/pages/dashboard/Home.tsx
  client/src/pages/dashboard/Tracking.tsx
  client/src/pages/leaderboard/index.tsx
  client/src/pages/profile/index.tsx
  client/src/styles/tailwind.css
  client/src/types/RanklistItem.ts
  client/src/utils/calculatePoints.ts
  client/yarn.lock
  nginx/default.conf
  server/package.json
  server/src/main.ts
  server/src/modules/app.module.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/parsers/parsers.service.ts
  server/src/modules/stats/stats.controller.spec.ts
  server/src/modules/stats/stats.controller.ts
  server/src/modules/stats/stats.module.ts
  server/src/modules/stats/stats.service.spec.ts
  server/src/modules/stats/stats.service.ts
  server/src/modules/submissions/submissions.controller.ts
  server/src/modules/submissions/submissions.service.ts
  server/src/modules/users/user.entity.ts
  server/src/modules/users/users.controller.ts
  server/src/modules/users/users.module.ts
  server/src/modules/users/users.service.ts
  server/src/validators/create-user-dto.ts
  server/src/validators/login-user-dto.ts
  server/test/fake-db-seed.ts
  server/yarn.lock
Labels: frontend, backend

#153 Import submissions through CSV file.
  client/src/components/Form.tsx
  client/src/components/Spinner.tsx
  client/src/components/layouts/Dashboard.tsx
  client/src/components/layouts/Settings.tsx
  client/src/components/submissions/AddEntryRow.tsx
  client/src/pages/dashboard/Home.tsx
  client/src/pages/dashboard/ImportCsvModal.tsx
  client/src/pages/dashboard/Tracking.tsx
  client/src/pages/leaderboard/index.tsx
  client/src/pages/settings/AccountSettings.tsx
  client/src/pages/settings/HandleSettings.tsx
  client/src/styles/tailwind.css
  client/src/utils/csvToArray.ts
  client/tailwind.config.js
  server/src/modules/submissions/submissions.service.ts
Labels: frontend
